# Generated by Django 5.2.7 on 2025-11-02 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_User_Table',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('locations', models.CharField(max_length=500, null=True)),
                ('current_school', models.CharField(max_length=500, null=True)),
                ('education', models.CharField(max_length=500, null=True)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female')], max_length=2)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=9, max_length=100, null=True)),
                ('profile_pic', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_data_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('text_area', models.CharField(max_length=9999)),
                ('image', models.ImageField(null=True, upload_to='post_images/')),
                ('n_like', models.DecimalField(decimal_places=0, default=0, max_digits=9999, max_length=9, null=True)),
                ('user_id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_Date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('Comment_Text', models.CharField(max_length=9999)),
                ('Comment_User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Comment_Post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facebook_App.facebookpost')),
            ],
        ),
        migrations.CreateModel(
            name='Friend_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('AP', 'Accept'), ('RJ', 'Reject')], default='PN', max_length=20)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL)),
                ('friend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('Post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facebook_App.facebookpost')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
