# Generated by Django 5.2.7 on 2025-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_table',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
