# Generated by Django 5.2.7 on 2025-11-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_App', '0002_alter_extra_user_table_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_table',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
