# Generated by Django 5.2.7 on 2025-11-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_App', '0005_alter_extra_user_table_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_user_table',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
    ]
